### ISSUE TITLE
Skip staging

### ISSUE THREAD

**Issue by mike-audi** [tiki/publish-sdk-android#47]
The current release script publishes to the sonatype staging repo. This requires manually logging in, closing the stage, and releasing the version. We want to skip that entire process. Once released via GH it should be live on Maven Central.

**Comment by ricardobrg** [comment]
This implementation started in #171. 

We are using [gradle-nexus-staging-plugin](https://github.com/Codearte/gradle-nexus-staging-plugin/) as per [Nexus docs](https://help.sonatype.com/repomanager2/staging-releases/configuring-your-project-for-deployment)

Still need some configuration, since it is failing to login ([401 error](https://github.com/tiki/tiki-sdk-android/actions/runs/4882363450/jobs/8712345226#step:10:46)). I will keep it open and testing in the next releases.

One thing that I might do if have spare time is to create SNAPSHOT releases that can be removed later to test it. The regular release cannot be removed. Since it is not an urgent issue, it is more plausible that I tune it in every release.
